### ISSUE TITLE
How to rearrange the column in case when more than 2

### ISSUE THREAD

**Issue by HocheolJang426** [ncborcherding/scRepertoire#122]
Hi
I'm trying to rearrange the column in using the function clonalDiversity
I have 6 columns in my data
The names of each are W0, W1, W3,W4, W12, W13

When I use the ClonalDiversity function, columns arranged in this order: W0, W1, W12, W13, W3, W4
But I want to order my column like this: W0, W1, W3, W4, W12, W13

How can I solve this problem?

**Comment by ncborcherding** [comment]
Hey HocheolJang426, 

Thanks for reaching out - would you mind telling me what version of scRepertoire you are using? This actually should be fixed in later versions - you can install with: 

```
devtools::install_github("ncborcherding/scRepertoire@dev")
```

If that is not an option for you - you could ```clonalDiverstiy(...,exportTable = TRUE)``` and set the order and plot yourself using ggplot. 

Let me know if this helps or if you have any more questions/issues.

Nick

**Comment by ncborcherding** [comment]
I am going to close this issue as newer version should account for this. But let me know if the issue persists for you.

**Comment by noranekonobokkusu** [comment]
The current master version rearranges sample names alphabetically because of lines [150-152](https://github.com/ncborcherding/scRepertoire/blob/master/R/clonalDiversity.R), which changes the original order of the samples. I don't know if this is intended, but it can be fixed by replacing these lines with
<pre>
mat_melt$Group = factor(mat_melt$Group, levels = names(input.data))
</pre>
