### ISSUE TITLE
TCR shared clones

### ISSUE THREAD

**Issue by Yvonne-Yue** [ncborcherding/scRepertoire#149]
**Hi！I'm wondering when perform this circlized plots to see their share clones like sentences below:**
  chordDiagram(circles, self.link = 1, 
             grid.col = grid.cols, directional = 1, 
             direction.type =  "arrows",
            link.arr.type = "big.arrow")
**Do the arrows here represent a certain differentiate direction of these clones? Like indicating their origin directions?**
Thank you！

**Comment by ncborcherding** [comment]
Hey Yvonne, 

Thanks for reaching out - short answer is no - the differentiation direction should not be inferred by ```getCirclize()```.

The ```getCirclize()``` generates a matrix similar to ```clonalOverlap()```. Then in order to not count clonotypes twice, it eliminates the reciprocal overlap. This elimination is done by the order of the **group.by** variable in alphanumeric order. So in the [vignette example](https://ncborcherding.github.io/vignettes/vignette.html#67_getCirclize) for the tumor-specific clonotypes:

![image](https://user-images.githubusercontent.com/22754118/159488972-a3084e93-f634-462e-adb7-fdb019caec9a.png)

Clusters are labeled C1-C12, therefore any overlapping clonotypes with C1 are eliminated and the arrows go from C1 to the other C2,C3,C4, etc. 

Hope that helps, I am going to close this as it is not a technical issue. But please feel free to continue the comment below. 

Nick
