### ISSUE TITLE
Subsetting data by partial CDR3 AA sequence

### ISSUE THREAD

**Issue by dhcorn** [ncborcherding/scRepertoire#157]
Hello,

This has been a wonderful program for most of the stuff I have wanted. Though I am trying to subset some of my TCR data by the CDR3 region, but I dont want to subset by the whole CDR3 AA sequence just a portion of it. For example I have tired the following code trying to look at the first 6 amino acids in the CDR3 without caring what the rest are:
>library(stringr)
>TCR <- SeuratObject@meta.data[str_detect(SeuratObject@meta.data$CTaa, '_CASSDWG'), ]
>head(GAP50TCR2)

However, when I do this my data turns from a seurat object to a dataframe with only the meta.data info so I can not re-cluster or look at the transcript info. Is there a way to keep this in a seurat object while at the same time subsetting my data with only a portion of the CDR3 region, or any region for that matter. 

Thanks in advance,

Doug

**Comment by ncborcherding** [comment]
Hey Doug,

Cool idea - yes this is caused by issues with how Seurat stores expression vs meta data. 

Given the above code, here is a workaround that might work, the first step is using your code to return the cell barcodes with the CTaa that match your pattern and then using the Seurat-friendly ```subset()``` to indicate you only want those specific cells. 

```
library(stringr)
TCR.cells  <- rownames(SeuratObject@meta.data[str_detect(SeuratObject@meta.data$CTaa, '_CASSDWG'), ])
TCR <- subset(SeuratObject, cells = TCR.cells)
```

Hope that helps and let me know if you have any other questions/suggestions.

Nick

**Comment by dhcorn** [comment]
That works great!

Thanks.

**Comment by amkhasawneh** [comment]
Hello.

Sorry for interfering like this, but trial and error (and mostly the latter) have taught me a more succinct method to subset Seurat Objects. Like Nick said, Seurat stores expression data, where the cell barcodes are column names; and metadata, where cell barcodes are row names. It might look confusing at first, but, in the subsetting structure with the square brackets, instead of putting the comma after the `str_detect()` function and its arguments, etc., you can put it _before_. This is probably because you're subsetting columns, as far as the Seruat Object "proper", if I may (as opposed to its metadata) is concerned.

I usually use something like this:

`TCR <- SeuratObject[,str_detect(SeuratObject@meta.data$CTaa, '_CASSDWG')]`

Also, please notice that, before the square brackets, it doesn't work if you add `@meta.data`, since you're not subsetting only metadata. Also, when square-bracket-subsetting, you don't really need `@meta.data`, either.

Sorry again.

I hope this helps, if only a little!

Abdullah.

P.S.: I am a complete newbie in the field, but I was wondering, isn't the CDR3 region in the _heavy_ chain of the BCR? I mean, shouldn't we be looking into the part of the CTaa that is _after_ the underscore?

**Comment by ncborcherding** [comment]
Hey Abdullah - Thanks for the post and example!

CDR3 regions are in each of the heavy and light chain - most of the field is focused on the CDR3 of the heavy chain though (similar to TCRB) as it is assumed to be more vital in antigen binding.

Nick

**Comment by amkhasawneh** [comment]
Thanks a lot, Nick!
