### ISSUE TITLE
combineTRUST4() function

### ISSUE THREAD

**Issue by yi-jun1** [ncborcherding/scRepertoire#165]
Hi Nick, I've found that combineTRUST4() will be very useful for me. However, I think the latest version of scRepertoire package (1.5.3) does not include that function (could not find function "combineTRUST4"). I tried to put the function by using the source code manually in my R studio, but the function is still not working (because of no subfunction like checkList() and cellT(), which are the shared function with the combineTCR function). I would be grateful if you check this function. Thanks!

**Comment by ncborcherding** [comment]
Hey June, 

Thanks for reaching out and sorry for the confusion.

The dev version (v1.5.3) has a new function ```loadContigs()```to allow for greater support of non-10X data formats (including TRUST4). This will eventually superscede combineTRUST4, so that all data is loaded the same and then can use ```combineTCR()```

Right now, the master branch (v1.5.2) still contains ```combineTRUST4()``` so might be a better option for you. 

Nick
