### ISSUE TITLE
changing the clonotype size

### ISSUE THREAD

**Issue by EAC-T** [ncborcherding/scRepertoire#171]
Can we change the slot size ?

slot(object, "meta.data")$cloneType <- factor(slot(object, "meta.data")$cloneType,
            levels = c("Hyperexpanded (100 < X <= 500)", "Large (20 < X <= 100)",
                    "Medium (5 < X <= 20)", "Small (1 < X <= 5)", "Single (0 < X <= 1)", NA))

instead I want it like this,

slot(object, "meta.data")$cloneType <- factor(slot(object, "meta.data")$cloneType,
             levels = c("Large (10 < X <= 20)", "Medium (5 < X <= 10)", "Small (1 < X <= 5)", "Single (0 < X <= 1)", NA))

But it didn't work, any idea why? 

Thank you

**Comment by ncborcherding** [comment]
Hey EAC-T,

Thanks for reaching out - yes you can change the **cloneType** groupings. This is actually done at the point of ```combineExpression()```. For the breakdown you want - here would be the code:

```
seurat <- combineExpression(combined, seurat, 
                  cloneCall="gene", 
                  group.by = "sample", 
                  proportion = FALSE, 
                  cloneTypes=c(Single=1, Small=5, Medium=10, Large=20))
```

The code you cite above actually changes the order of the **cloneType** factor so that the color palette matches the sizes. 

Let me know if you have any other questions.

Nick
