### ISSUE TITLE
Error in combineExpression

### ISSUE THREAD

**Issue by meaksu** [ncborcherding/scRepertoire#202]
Hi,
I am getting an error when trying to use the combineExpression function.

`list.receptors <- c(combinedTCR, combinedBCR)`
`seurat_obj <- combineExpression(list.receptors, seurat_obj, cloneCall = "gene", group.by = "sample", proportion = TRUE)`
`Error in '$<-.data.frame'('*tmp*' "cloneType", value = NA) : 
  replacement has 1 row, data has 0
`

The same error happens when using either combinedTCR or combinedBCR alone, so I don't think it's a related to using them both in a list. Do you know what could be causing this?

**Comment by ncborcherding** [comment]
Hey Meaksu, 

Thanks for reaching out - could you give me a little more information?

Things that would be helpful:

1. What are the outputs of ```head(combinedTCR[[1]])``` and ```head(combinedBCR[[1]])```?
2. How many samples are you combining in both the combinedTCR and combinedBCR?
3. What is the output of ```head(seurat_obj@meta.data)```
4. What version of scRepertoire are you using?

Thanks,
Nick

**Comment by meaksu** [comment]
Hi,
Here are the answers to your requests - 

1.
![Capture](https://user-images.githubusercontent.com/71838948/199086176-732ebe30-826c-4543-bebb-dc97978f607b.PNG)

2. combinedTCR and combinedBCR each have 32 samples for a total of 64 samples.

3. 
![Capture](https://user-images.githubusercontent.com/71838948/199086490-95a00186-86a1-4761-bb72-3572d2d86597.PNG)

4. Version 1.7.2

Thanks

**Comment by ncborcherding** [comment]
Hey meaksu, 

Looks like you are running into a pretty common problem - barcode mistmacth between the combineTCR/BCR output and the seurat object. 

Seurat Object Barcodes:
<img width="231" alt="Screen Shot 2022-11-01 at 5 26 44 AM" src="https://user-images.githubusercontent.com/22754118/199213556-c7d7eb88-d7fa-4507-ba38-7f23cb025e74.png">

combineTCR/BCR Barcodes: 
<img width="319" alt="Screen Shot 2022-11-01 at 5 27 03 AM" src="https://user-images.githubusercontent.com/22754118/199213652-c990072d-e84c-472d-a5d2-fd8d7f681555.png">

In order to get combineExpression() to work, you'll need to modify the barcodes (the seurat object would probably be the easiest).

Let me know if you have any questions, 

Nick

**Comment by ncborcherding** [comment]
Hey meaksu, 

I am going to close this issue due to the lack of response. If you continue to have this issue of barcode mismatch, please let me know and I can help troubleshoot.

Nick
