### ISSUE TITLE
Error with the no. of barcodes varying from raw contigs to combined contigs after CombineTCR function

### ISSUE THREAD

**Issue by apal6** [ncborcherding/scRepertoire#233]
Hi Nick,

I am wondering why the number of barcodes (clones) decreasing and increasing when trying to use combineTCR function on two samples. 
My timepoint 0 has 17966 samples and timepoint 10 has 2300 samples but after combining, that gets reduced to 1211 and 8255 respectively. Is there anything I am missing or doing wrong when combining?

I am not sure how exactly it is combining which its kinda like swapping the values. 

`contig_day10<- read.csv("Day10/filtered_contig_annotations.csv")
contig_day10$barcode%>% #day10
+   length()
[1] 2300 
contig_day0 <-read.csv("Day0/filtered_contig_annotations.csv")
contig_day0$barcode%>% #infusion
+   length()
[1] 17966
contig_list <- list(contig_day0, contig_day10)

combined <- combineTCR(contig_list,samples = c("day10", "day0"), cells ="T-AB",removeNA = FALSE,
                       removeMulti = FALSE,
                       filterMulti = FALSE)
combined[[1]]$barcode%>% #day10
  length()
[1] 8255
combined[[2]]$barcode %>% #day0
  length()
[1] 1211

`
Would appreciate your help! 

Thank you,
Aastha

**Comment by ncborcherding** [comment]
Hey Aastha,

Apologies Im responding on my phone.

`combineTCR()` is generating clonotypes by barcodes in order to interact with your single-cell object. During this process, the TRA and TRB chains from the contig file are actually combined to form 1 line. So you are actually see roughly 1/2 the numbers as the out for `combineTCR`, which is what you should expect (TRA and TRB chains/2).

I have a conference tomorrow, but I plan on taking a look at the code you sent Wednesday. In the meantime, let me know if you have any questions and I can follow up then too.

Nick
