### ISSUE TITLE
scRepertoire  example data

### ISSUE THREAD

**Issue by tuqiang2014** [ncborcherding/scRepertoire#25]
dear   scRepertoire   team:

Thanks for  your  great job. [scRepertoire](https://github.com/ncborcherding/scRepertoire) When I  try  `scRepertoire`  demo, I can not  download  **seurat data** . Can I get the data from other sources, or  , could you send me the data by email?

Thanks.

**Comment by ncborcherding** [comment]
Hey tugiang2014,

Not sure if you still need the data after closing the issue, but wanted to ensure that you and others knew where to get it.

The scRepertoire package has data built into it (see the vignette in the package itself). This is the **"screp_example"** data, which is randomly sampled from the larger cohort of renal cell carcinoma (this is due to size issues).

However, I wanted to show how scRepertoire could be used on data sets of substantial size, so the vignette posted on the readme file is actually using the full renal cell carcinoma. Because this object is > 400 mB, I am making it accessible via [this google drive](https://drive.google.com/open?id=1np-EzG7U9W_Fz_SchBrsAhtqE3_rB_H9) link.

Hope that helps and let me know if you run into any issues.
