### ISSUE TITLE
Clonotype observed in both CD4 and CD8 T cell population

### ISSUE THREAD

**Issue by nicodemus88** [ncborcherding/scRepertoire#260]
Hi, 
Wanted to ask if you've seen something similar to this. 
I have a scRNA-seq and scTCR-seq of tumor-infiltrating T cells. 
I merged the samples then used combine expression to joint the TCR information. 
I've checked many times, but there seems to be no mistake with the barcoding. 
However, I can see that some clones in the CD4 population are found in the CD8 population, which doesn't seems to be right. 
Does anyone face this kind of issue before? 

![clonotype](https://github.com/ncborcherding/scRepertoire/assets/24598265/9881ec5d-ada7-4166-8b81-5e0c9eeadb43)

**Comment by ncborcherding** [comment]
Hey nicodemus, 

Are the cell types based on flow sorting or single-cell GEX annotation? Both approaches will have some level of "contamination" between CD4 and CD8. It is actually pretty common if these are based on single-cell GEX annotation to get a top clone shared between CD4 and CD8 lineages, based on the difficulty of annotating true "CD4" T cells. If these are flow sorted, I would not expect a top clone to be shared. 

Happy to discuss more - let me know what kind of info you can provide. 

Nick

**Comment by nicodemus88** [comment]
Hi ncborcherding, 
Well, we flow sorted CD3+ cells only which are then loaded to 10X and the annotation are based on GEX. 
So in this case, how should we consider these overlapping clones caused by this "contamination"? 
I couldn't exclude them completely as some of these are really interesting for us - for example, the green clone above which is expanded in the metastatic site.

**Comment by ncborcherding** [comment]
"Contamination" is probably not the best word for this but separating CD4 and CD8 populations via GEX has some pitfalls due to the relatively low feature space of T cells via single-cell assays and the low expression of CD4 mRNA in general. I don't think you should exclude either, but refining you annotations might help - such further separating them into clusters, using something like [projectTIL](https://github.com/carmonalab/ProjecTILs). 

Nick
