### ISSUE TITLE
Merge the samples

### ISSUE THREAD

**Issue by mainyanghr** [ncborcherding/scRepertoire#306]
Dear Nick,

1: Please see the attached pic.  I am wondering how to merge the "two-sub samples (such as , p3EC and p3LP)" together as a "whole sample" in order to compare (clonalCompare) with other "whole samples".  In another words, how should I create a new list called p3ALL to replace the current p3EC and p3LP?

2: Please see the attached pic and I created a inflammation column. How should plot the specific order based on the inflammation status by clonalAbundance?   The following code does not work.
TCRall <-TCRall[c("Bnoinflammed",  "Binflammed",  "Anoinflammed",   "Ainflammed")]
`clonalAbundance(
  TCRall,
  cloneCall = "strict",
  chain = "both",
  scale = FALSE,
  group.by = "inflammation",
  exportTable = FALSE,
  palette = "inferno")`

Thank you very much kind help!

<img width="299" alt="Screenshot 2024-01-12 at 16 29 25" src="https://github.com/ncborcherding/scRepertoire/assets/146676920/3f9db4d1-75c0-4f9e-adbe-250222828064">

**Comment by ncborcherding** [comment]
Hey mainyanghr,

Thanks for reaching out. 

1. In terms of grouping - it looks like you have the patient level annotation in the data. You should be able to just use the **group.by** parameter in scRepertoire functions to combine them for the purpose of visualizations or analysis. 

2. We have been working on making the plot ordering more adaptive - this should be fixed in the most recent github version. You can install that with: 

```
devtools::install_github("ncborcherding/scRepertoire")
```

Just make sure you restart your R session and I think you should be good to go.

Nick
