### ISSUE TITLE
Differences in diversity analysis when using other packages

### ISSUE THREAD

**Issue by abedkurdi** [ncborcherding/scRepertoire#334]
Hello there,

I was comparing the diversity plots, output from your package `scRepertoire` and output from another package called `djvdj`, available on GitHub.

I thought I would be able to reproduce, if not identical results, something very similar when using both packages. However, it was not the case:

The following screenshot is the output using your package:
![311703300-dd4c7f07-5cc1-4a07-a8e4-c0b5df50b8c6](https://github.com/ncborcherding/scRepertoire/assets/45813669/a6d704fc-20be-4001-be7c-9b13809abbc9)

and the second one is from the other package:
![311703265-becee6bd-9c24-43c9-9af9-d7a43ac7ed27](https://github.com/ncborcherding/scRepertoire/assets/45813669/5b51bb8f-3842-471c-b7f2-852061da270c)

I appreciate it a lot if you can help me in this, or if you have any hints that can pinpoint what is happening.

Thanks so much!

**Comment by ncborcherding** [comment]
Hey Abdullah, 

My guess is that it is do to downsampling - the default for djvdj is to not downsample, whereas scRepertoire is to downsample. Additionally, because of the random sampling that occurs in downsample, you are likely not going to see exact result matches. 

You can try to skip the bootstrapping using and look at the comparison:

```
clonalDiversity(..., skip.boots = TRUE)
````

**Comment by abedkurdi** [comment]
Thanks for your prompt response! 

I could not find `skip.boots` parameter in `clonalDiversity` function. I have `scRepertoire` version 1.12.0

**Comment by abedkurdi** [comment]
Indeed! it was all about the downsampling!

Thank you so much!!
