### ISSUE TITLE
Use mixcr findShmTrees output as a clone_call for BCR

### ISSUE THREAD

**Issue by MathildeFogPerez** [ncborcherding/scRepertoire#336]
Hi @ncborcherding thank you so much for developing scRepertoire this is a really great tool!

Soon I'll be working with BCR + scRNA data and I would like to use MiXCR for the analysis of clones trees (findShmTrees function from MiXCR platform) and then use scRepertoire to follow clonotypes combined with transcriptomics data etc.. and to use all nice functions you have!

I thought I could combineBCR with the default parameter and overwrite CTaa field for example with the Id of the trees found by MiXCR, to have the exact same clonal families/trees in both analysis.

Do you think it could work? I guess CTaa is taken as a single string and if I replace by a tree Id it should work the same.

@PoslavskySV  if you have better idea, let me know.

thanks a lot in advance

best,
Mathilde

I

**Comment by ncborcherding** [comment]
Mathilde, 

Thanks for reaching out - I am still trying to think through how better to incorporate other workflows into scRepertoire, so your issue is pretty poignant. 

That should work if you have everything structure at the individual barcode level. You could use the CTstrict column, as you will have a more comprehensive lineage call from MiXCR and CTstrict has some redundant sequence data.

Let me know if you run into any issues - I am happy to write whatever code you need, it might actually help with the above integrations. 

Thanks,
Nick

**Comment by MathildeFogPerez** [comment]
Hi Nick, 

Thank you so much for your answer! I let you know if I ran into any issues. 
I'm trying to think of the best pipeline for our analysis, I will get the data in few months if everything go smoothly.
thanks again

Mathilde
