### ISSUE TITLE
Issue with "group.by" for clonalOverlap

### ISSUE THREAD

**Issue by sc30301** [ncborcherding/scRepertoire#354]
I am encountering an issue where when I use a different variable for "group.by" while using clonalOverlap. I still get the overlaps for samples. This doesn't seem to be an issue with other functions like clonalQuant. 

Would it also be possible to allow users to specify the ordering of variables for plotting purposes? For barplots like clonalQuant it is easy to reorder the  X-axis variables but for clonalOverlap the ordering is compromised using a function like scale_x_discrete.

**Comment by ncborcherding** [comment]
Happy to add it to the to do list for future features - could you provide a reproducible example of exactly what you are talking about. 

Thanks,
Nick

**Comment by sc30301** [comment]
Sure. I have 6 samples that belong to 3 groups which I add using `addVariable`:

`ex <- addVariable(ex, variable.name = 'group', variables = c('G1', 'G1', 'G2', 'G2', 'G3', 'G3'))`

Output of `clonalOverlap` without grouping: 

![image](https://github.com/ncborcherding/scRepertoire/assets/67088673/1f485864-0124-45ab-bf5c-4eb33d205f12)

When I specify `group.by = 'group'` the output remains unchanged. This is the output of clonalQuant when specifying `group.by='group'`, however:

![image](https://github.com/ncborcherding/scRepertoire/assets/67088673/c371b2bb-6438-4589-a38c-2d8945e9f5ee)

With regards to the ordering issue, here is an example for if I want to change the order of the axes: 

`clonalOverlap(ex, method = 'morisita') + scale_x_discrete(limits = c('P2', 'P3', 'P6', 'P4', 'P1', 'P5')) + 
  scale_y_discrete(limits = c('P2', 'P3', 'P6', 'P4', 'P1', 'P5'))`

![image](https://github.com/ncborcherding/scRepertoire/assets/67088673/ea24a6ab-de64-4a78-b81c-09985706ee8c)

**Comment by ncborcherding** [comment]
Did push a fix (to the dev branch) so that you should be able to reorder the sample-level plotting by just reordering the list elements (this should have been implemented already for ```clonalOverlap()```. I will get it tested more thoroughly and push it to the master branch here as soon as I can.  See example below.

```
combined <- combineTCR(contig_list, 
                        samples = c("P17B", "P17L", "P18B", "P18L", 
                                              "P19B","P19L", "P20B", "P20L"))
clonalOverlap(
      combined[c(3,4,1,2,7,8,5,6)], 
      method = "raw")
```

<img width="631" alt="Screenshot 2024-04-18 at 5 46 54 PM" src="https://github.com/ncborcherding/scRepertoire/assets/22754118/45eb7586-966b-4175-ba5d-e48117183d18">

I think the open problem here still is if you are using a **group.by** variable such as your "group" - because the reorganization of the data is internal to the function - there will need to be a new optional parameter for order in, I think, all viz function calls. I will work on that as I get time. 

Thanks for letting me know and following up with the excellent run down.

Nick

**Comment by sc30301** [comment]
Great, thank you Nick!
