### ISSUE TITLE
Combine contig_list

### ISSUE THREAD

**Issue by jsmoon4** [ncborcherding/scRepertoire#4]
Thanks to this helpful tool!
I want to analyze cells with combined data of TCR Clonotype and gene expression.
I am a new user of R, so I want to ask some basic questions.
I loaded 6 filtered_contig_annotation.csv files and listed with 
`contig_list <- list(csv3, csv4, csv5, csv6, csv7, csv8)`
In my files, the barcode is just like AAACCTGAGAGTGACC-1.
So, I didn't strip barcodes. And, I wanted to combine contigs with following code.
`combined <- combineContigs(contig_list, samples = c("P2", "P2", "P3", "P3", "P4","P4"), ID = c("Pre", "Post", "Pre", "Post", "Pre", "Post"), cells ="T-AB")`
6 files are divided into 3 patients and 2 status in each patient.
However, there was an error message.
> Error in strsplit(df[[1]]$barcode[1], "[-]") : non-character argument

I would like to ask what code is wrong to combine contigs.
Many thanks.

**Comment by ncborcherding** [comment]
Hey - thanks for the question.

What is the output of `class(csv3$barcode)` ? My first guess is this is a factor instead of a character, which could be solved by loading the files like `csv1 <- read.csv(file1.csv, stringsAsFactors = F`

But if that is not it, please feel free to include anything up to the point of calling combineContig() so I can try to recreate the problem from my end to help.

**Comment by jsmoon4** [comment]
Thanks to your quick response.
As your comment, I add stringsAsFactors = F in that code.
And, the CombineContig() works well. 
Also, I want to ask how to reorder ID status. As I said, ID status contains "Pre" and "Post".
In the graph of Percent of unique Clonotype, the order is "Post" and "Pre".
How can I change the order to "Pre" and "Post" in the graph?
Many thanks.

**Comment by ncborcherding** [comment]
Easiest fix for that is come up with a different naming scheme - like "Before" and "Post". The graph is going to go in alphabetical order unless you assign a specific order to the levels. The problem is there is no way to call and order the levels before the graph because it's embedded in the function.

Depending on your familiarity with R/ggplot, an alternative would be:
`quantContig(df, exportTable = T)`` and then graph the output. You could then order your samples by using `quantContig_output$sample <- factor(quantContig_output$sample, levels = c("specific", "order", "you", "want", "for", "all", "samples")` and plot it yourself in ggplot or other plot functions?

Let me know if that make sense, for connivance for other, I am going to mark this issue as closed, but if you have other questions, feel free to email me at ncborch@gmail.com.

**Comment by jsmoon4** [comment]
Thank you for the suggestions. I just changed the name with the alphabetic order and it works well.
