### ISSUE TITLE
filterMulti option

### ISSUE THREAD

**Issue by paolo-kunderfranco** [ncborcherding/scRepertoire#41]
Hi,
I am a bit confused of the output of filterMulti=TRUE or FALSE

For example, 

- highlighted in  yellow are barcodes selected **only** with option == FALSE

- highlighted in  green are barcodes selected **only** with option == TRUE

- highlighted in  orange are barcodes selected **both** with option == FALSE or option == FALSE

https://drive.google.com/file/d/1qnVbHpgMnZeBmeXt1h9Uw3TEzP3SiC5o/view?usp=sharing

Could you please comment?

best
Paolo

**Comment by ncborcherding** [comment]
Hey Paolo,

**filterMulti** is used to remove the TCRA/B chains for a single cell barcode that are not within the top 2 sequences by number of reads. This allows for clonotype to be assigned by the top TCRA and top TCRB chain. 

<img width="813" alt="Screen Shot 2020-11-18 at 9 37 31 AM" src="https://user-images.githubusercontent.com/22754118/99551695-c6565a00-2981-11eb-9966-1d715157de35.png">

So using your first set of clonotypes as an example:

- Row 4 and 5 will be removed as they are neither productive nor full length
- Then, if **filterMulti = T**, the function will look at the number of reads and assign the top TCRB and top TCRA as the clonotype.

**filterMulti** will not remove a TCR chain when 2 V genes have been assigned, so row 1 from the below table you sent.

<img width="808" alt="Screen Shot 2020-11-18 at 9 44 48 AM" src="https://user-images.githubusercontent.com/22754118/99552592-cc006f80-2982-11eb-8b1e-f9a47ce4a864.png">

Nor will it affect barcodes that only have 2 productive TCR chains, like:

<img width="808" alt="Screen Shot 2020-11-18 at 9 50 10 AM" src="https://user-images.githubusercontent.com/22754118/99553239-8a23f900-2983-11eb-9519-9f218c1bb41a.png">

I am not exactly sure what you mean by:

> highlighted in orange are barcodes selected both with option == FALSE or option == FALSE

Hope that helps, feel free to keep asking questions, this will be a good reference for other users.

Thanks,
Nick

**Comment by paolo-kunderfranco** [comment]
highlighted in orange are barcodes selected both with option == FALSE or option == TRUE

**Comment by paolo-kunderfranco** [comment]
if filterMulti = T, why barcodes highlighted in yellow are discarded form the contig_list?

**Comment by ncborcherding** [comment]
Hey Paulo - 

**filterMulti** is used to create just 2 chains per barcode: 1) TCR A chain and 2) TCR B Chain. In the yellow example, there are only 3 chains that are productive (the nonproductive chains will be filtered out). The **filterMulti** parameter is only removing 1 chain. **removeMulti** would eliminate all the barcodes highlighted in yellow.

Orange highlights only have 2 productive clones - so the **filterMulti** parameter will not affect them.

Feel free to provide you `combineTCR()` calls for the 3 colors.

**Comment by paolo-kunderfranco** [comment]
Hi, thanks, I shared you a Gdrive folder.
paolo

**Comment by ncborcherding** [comment]
Hey Paolo,

Thanks for sharing the code - now I see what you are talking about. For the `combineTCR()` you are comparing the difference between `combineTCR(removeNA=TRUE, filterMulti=TRUE)` versus `combineTCR(removeNA=TRUE, filterMulti=FALSE)`. 

Why you are getting a difference between the 2 calls is **filterMulti** works before **removeNA** by design - filterMulti will remove extra TCR chains for barcodes with > 2 chains (this includes productive chains with NA values that are not the two most highly-expressed chains). Thus `combineTCR(removeNA=TRUE, filterMulti=TRUE)` will preserve some barcodes (but not all) with NA values before removing NA values. So the difference you are seeing of 5.2% and 2.6% is the product of this set up. 

Hope that helps,
Nick

**Comment by paolo-kunderfranco** [comment]
Ok, but which one do I have to use, because in both examples some nice barcodes are filtered out!
Or not?

**Comment by ncborcherding** [comment]
So I think most users if interested in true definitions of clonotype will want `combineTCR(removeNA=TRUE, filterMulti=TRUE)` This is a balance of stringency and leads to the recovery of the most barcodes with 1 alpha chain and 1 beta chain (without those being assigned as NA values). With currently developing some next level analyses for single-cell clonotypes, this is what I typically use. 

There is no right answer here though, because a lot of T cell clonotype analyses use TCRB - so filteringNA might not be great for people interested in that (as TCRA NA values >> TCRB NA values) or other users might be interested in why there are more than 2 productive TCRA or TCRB chains.

Thanks Paolo for bring up this point - I think it is a pretty important for users to think about how their inputs will affect downstream analyses.
