### ISSUE TITLE
How to use combineTCR and combineExpression with multiple samples?

### ISSUE THREAD

**Issue by HousLi** [ncborcherding/scRepertoire#51]
Hello, 

Thanks for the wonderful package! 

I have two questions regarding combining more than 6 samples,

1. Can I use combineTCR() for more than 6 samples? Is there any way to merge multiple contig_lists into one combined contig?
2. When attaching VDJ information using combineExpression(),  can I attach multiple combined contigs?

Thank you! 
Hous

**Comment by ncborcherding** [comment]
Hey Hous,

Yes scRepetoire can be used with more than 6 samples - the actual vignette is 3 samples with 2 sequencing runs each - both a peripheral and tumor-infiltrating immune sequencing runs. I have used the package for 47 sequencing runs across 20+ samples. 

**Can I use combineTCR() for more than 6 samples? Is there any way to merge multiple contig_lists into one combined contig?**

So in the context of maybe more than 1 sequencing run for the sample sample? You can use the **rbind()** function on the contig objects before forming you list. 

For example
```
contig1 <- read.csv(xxxxx1.csv) #assuming the above
contig2 <- read.csv(xxxxx2.csv)
contig <- rbind.data.frame(contig1, contig2)
```
If however you have the sequencing runs across a single sample in different tissues - such as the case for the vignette in peripheral blood and tumor-infiltrating immune populations, I would think about maintaining each as elements in the contig_list.

**When attaching VDJ information using combineExpression(), can I attach multiple combined contigs?**

**combineExpression() **is going to do 2 things: 1) count the frequency of clonotypes and 2) attach to the meta data of the single cell object using the barcodes. As long as the barcodes in both the single cell object and combined contig object match, there should not be an issue. 

Let me know if you have any additional questions or issues you run into, more than willing to help get you started. I am going to close this issue because it is not a code-related, but feel free to keep commenting below. 

Thanks,
Nick

**Comment by HousLi** [comment]
Hi Nick, 

Thanks for your quick response! These are really helpful! 

Best, 
Hous
