### ISSUE TITLE
combineTCR should be able to ignore sample and ID 

### ISSUE THREAD

**Issue by Tianran1** [ncborcherding/scRepertoire#60]
When I use the combineTCR function, I must give the sample and ID parameter otherwise the function just failed.
It's not reasonable. Please check for that. Thanks you.

**Comment by ncborcherding** [comment]
Hey Tianran1,

That is by design to prevent issues with duplicate barcodes downstream. There have been several issues in the repo discussing methods to remove the ID afterwards [here](https://github.com/ncborcherding/scRepertoire/issues/22#issuecomment-672340223) and [here](https://github.com/ncborcherding/scRepertoire/issues/34).

I am open to suggestions on how you might change the function and still prevent duplicate barcodes, but for now the sample and ID length match is a feature. 

Thanks,
Nick
