### ISSUE TITLE
Alluvial plot fails if "cluster" stored in meta data 

### ISSUE THREAD

**Issue by mihem** [ncborcherding/scRepertoire#78]
Hi Nick,

just a tiny problem with this great tool.

I had my cluster names stored in `seu@meta.data$cluster` , but then `scRepertoire::alluvialClonotypes` failed with 

```
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
```

traceback:

```
10: stop(fallback)
9: signal_abort(cnd)
8: abort("Can't transform a data frame with duplicate names.")
7: initialize(...)
6: DataMask$new(.data, caller_env)
5: mutate_cols(.data, ..., caller_env = caller_env())
4: mutate.data.frame(., H.clonotypes = ifelse(meta[, cloneCall] %in% 
       color, "Selected", "Other"))
3: mutate(., H.clonotypes = ifelse(meta[, cloneCall] %in% color, 
       "Selected", "Other"))
2: meta %>% mutate(H.clonotypes = ifelse(meta[, cloneCall] %in% 
       color, "Selected", "Other"))
1: scRepertoire::alluvialClonotypes(sc_rep, cloneCall = "gene", 
       y.axes = c("Patient", "seurat_clusters", "Type"), color = "seurat_clusters")
```

After renaming the column "cluster" everything works fine. That's probably because alluvialClonotypes creates a column called `cluster`. Maybe using a different, more uncommon columname than `cluster` in the function, or renaming `cluster` if existent in the function, could solve this?

Best,
Mischko

**Comment by ncborcherding** [comment]
Hey Mischko, 

Thanks for reaching out and the characterizing the issue well. 

This is actually a result not of ```alluvialClonotypes()```, but from an internal function that grabs the meta data from single cell object, called ```grabMeta()``` Just commited the change so that this function now assess the colnames of the meta data before just assigning **cluster** as a header. Should be fixed now if you re-install from the github repo (master or dev branch). Just remember to restart your R session after reinstalling. 

Thanks again - this was a great suggestion.

Nick
