### ISSUE TITLE
Visualization outputs and interpretations for Seurat combined and expression2ListCluster objects

### ISSUE THREAD

**Issue by denvercal1234GitHub** [ncborcherding/scRepertoire#92]
Hi Nick, 

I hope all is well. Whenever you get a chance, would you mind helping me clarify the following points? Thank you a lot for your extraordinary help! Version = 1.3.2

**1. Setting combineExpression(combined Seurat object, groupBy = “ID”, proportion = F). If “ID” in my data is R5+ and R5- from 3 donors.** 

1a. Does this mean for each cell, a frequency is calculated as how many times that clone appears in each donor separately but across R5+ cells and R5- cells? 

1b. And, the frequency in all the downstream functions is calculated similarly as defined in 1a, even if I set groupby = some variable other than "ID"?

**2a. In the compareClonotypes() plot, I think each color represents a unique clonotype.** But when I looked at the legend, why do different clones appear to have the same color shown below (e.g., the green clones shared between the last 2 columns)? This is also evident when looking at the different bar within a column, appearing to have the same color but they are different unique clone right? The issue is independent of whether I called the clone by CTstrict or by CTaa.

<img width="237" alt="Screen Shot 2021-07-13 at 10 53 47 AM" src="https://user-images.githubusercontent.com/62179082/125431839-9ce84d20-2170-452e-aa12-8f17e08c2794.png">

<img width="1000" alt="Screen Shot 2021-07-13 at 11 03 23 AM" src="https://user-images.githubusercontent.com/62179082/125433273-9af3089c-01ae-47f4-a0ab-ccf5d44f2bc5.png">

**2b. It looks like the last 2 columns have a lot of shared clonotypes** in which the proportion increase from the left column to the right (last) column in proportion (and the proportion was calculated by the number of a unique clone divided by the total number of all clones in that variable column). There is a very faint line between the first (far left column) and the middle column. But, what happens if there is a clone that is shared between the first column and the last column? 

<img width="212" alt="Screen Shot 2021-07-14 at 2 27 40 PM" src="https://user-images.githubusercontent.com/62179082/125630001-0c139815-e713-4d1b-9fd5-c068b27cfed2.png">

**2c. What are the black blob in these columns represent?** I check your F1000Research paper and it is annoted as "single clonotype"(separate colors) and "multiple clonotypes" for the rest in Figure 4F.

**3. In this compareClonotypes() graph of expression2ListCluster object,** it looks like cluster 20 and 22 do not share any clonotype with any other cluster. But, when I graphed the regular combined Seurat object (with TCR info transfered) in a chordDiagram, there seems to be faint line going from cluster 20 and 22 to other clusters. Why is there a discrepancy?

<img width="181" alt="Screen Shot 2021-07-14 at 4 40 37 PM" src="https://user-images.githubusercontent.com/62179082/125650891-721319ee-1163-443a-8cce-4f95e63496a1.png">

<img width="286" alt="Screen Shot 2021-07-14 at 4 48 30 PM" src="https://user-images.githubusercontent.com/62179082/125652144-ff91fc6a-790d-4438-b95a-3575e5e7b78a.png">

**4. What is the "value" and the first column in the output of getCirclize(groupBy="cluster") of the chordDiagram below?** I used the default parameters, so I guess the smaller numbers around the outter of the circle represents the number of unique clones?

<img width="597" alt="Screen Shot 2021-07-13 at 1 41 46 PM" src="https://user-images.githubusercontent.com/62179082/125453268-eac81b89-49bb-4f9a-babb-d53eb3b50b0c.png">

**5. You mentioned "Using the relative number of unique and overlapping clones,** but is not using the clonotypes themselves to measure of relative clonotype overlap between groups and does not reflect exact clonotype matches between groups." for chordDiagram(). What does it mean? I thought for example in the plot in question 4 above, it shows whether a cluster has any unique clonotype that is shared with other clusters, and the width would just indicate whether that clone expands in the receiving end cluster?

**6. Is the warning from chordDiagram an error of concern?**

<img width="417" alt="Screen Shot 2021-07-13 at 12 47 23 PM" src="https://user-images.githubusercontent.com/62179082/125446500-00deaa30-e032-4b97-adf6-03af8b885f64.png">

**7. From this clonalOverlap(), the orange indicates the highest overlap coefficient** between sample A and sample B (i.e., sample A have much more clonotypes that are also present in sample B than other samples). But, when I plotted using clonesizeDistribution(), why were sample A and B on an entire oppsite branch of the tree below?

<img width="415" alt="Screen Shot 2021-07-14 at 2 44 36 PM" src="https://user-images.githubusercontent.com/62179082/125632673-5aa37275-1e18-4a05-8309-423091f04036.png">

<img width="450" alt="Screen Shot 2021-07-14 at 2 44 52 PM" src="https://user-images.githubusercontent.com/62179082/125632709-65e52935-1d29-497f-9ef9-d928b6f0f91c.png">

**8. scatterClonotype() says** "The clonotypes will be categorized by counts into singlets or multiplets, either exclusive or shared between the selected samples." From the plot below, does it mean the red dots are the clones that are shared between the 2 samples graphed? And, the size of the dots represent the sum of the this clone count in sample A and sample B? 

<img width="346" alt="Screen Shot 2021-07-14 at 2 52 48 PM" src="https://user-images.githubusercontent.com/62179082/125633996-ab6fba2b-d5dc-4d21-b1cf-fa4cdd966071.png">

**9. alluvialClonotypes() plot shows whether there is a unique clone** that shared among 3 variables (3 columns). But the middle column for example representing the number of clusters 0-22. Why this numbering is not in order; is it because it is arranged by how big the overlap in proportion of a unique clonotype? 

<img width="198" alt="Screen Shot 2021-07-14 at 4 42 57 PM" src="https://user-images.githubusercontent.com/62179082/125651267-154ee3e9-6864-47a6-8707-8e70302d06c3.png">

**10. clusterTCR() clusters** the clones by how similar their sequences are. Is the x-axis different cluster ID?

<img width="591" alt="Screen Shot 2021-07-14 at 2 59 04 PM" src="https://user-images.githubusercontent.com/62179082/125634928-0e9ccf7c-ffe8-4a0d-b04f-d7069094e238.png">

**11. quantContig() graph** appears to have orange/red color groups and then a more blue on the right side. Is there any meaning behind this color scheme?

Again, thank you so much, and apologies for having so many questions...

**Comment by ncborcherding** [comment]
I hope all is well. Whenever you get a chance, would you mind helping me clarify the following points? Thank you a lot for your extraordinary help! Version = 1.3.2

> 1. Setting combineExpression(combined Seurat object, groupBy = “ID”, proportion = F). If “ID” in my data is R5+ and R5- from 3 donors.
> 
> 1a. Does this mean for each cell, a frequency is calculated as how many times that clone appears in each donor separately but across R5+ cells and R5- cells?

No the frequency is calculated by "ID" so as you have written the code, the current frequency is based across all three samples placed in either R5+ or R5-. If you wanted to calculate by each donor, you would set **groupBy** = "sample". Or across sample and ID, just leave the **groupBy** variable blank

> 1b. And, the frequency in all the downstream functions is calculated similarly as defined in 1a, even if I set groupby = some variable other than "ID"?

A function with **groupBy** in down or upstream will calculate the frequency on the fly for that function call. 

> 2a. In the compareClonotypes() plot, I think each color represents a unique clonotype. But when I looked at the legend, why do different clones appear to have the same color shown below (e.g., the green clones shared between the last 2 columns)? This is also evident when looking at the different bar within a column, appearing to have the same color but they are different unique clone right? The issue is independent of whether I called the clone by CTstrict or by CTaa.

This looks like it is due plotting too many clones at once - you have maxed out the base color palette for ggplot. (This is my guess).

> 2b. It looks like the last 2 columns have a lot of shared clonotypes in which the proportion increase from the left column to the right (last) column in proportion (and the proportion was calculated by the number of a unique clone divided by the total number of all clones in that variable column). There is a very faint line between the first (far left column) and the middle column. But, what happens if there is a clone that is shared between the first column and the last column?

Based on the use of ggalluvial in other settings - if a column in between does not have shared clones, the alluvial/cord will be dropped. However, the stratum (the bar plot) will reappear in the third column with the same color.

> 2c. What are the black blob in these columns represent? I check your F1000Research paper and it is annoted as "single clonotype"(separate colors) and "multiple clonotypes" for the rest in Figure 4F.

The black color is derived from the outline of each individual stratum, if there is only 1 copy of the clone, they appear black. So it is in fact a series of single copy clones. 

> 3. In this compareClonotypes() graph of expression2ListCluster object, it looks like cluster 20 and 22 do not share any clonotype with any other cluster. But, when I graphed the regular combined Seurat object (with TCR info transfered) in a chordDiagram, there seems to be faint line going from cluster 20 and 22 to other clusters. Why is there a discrepancy?

Can you send me a copy of you ```expression2List()``` - I will need to look at the specific data to be able to see what is going on.

> 4. What is the "value" and the first column in the output of getCirclize(groupBy="cluster") of the chordDiagram below? I used the default parameters, so I guess the smaller numbers around the outter of the circle represents the number of unique clones?`

Value is the shared clonotypes between the clusters - but please do send me the data - cause that is showing shared clones in cluster 22 for some reason.

5. You mentioned "Using the relative number of unique and overlapping clones, but is not using the clonotypes themselves to measure of relative clonotype overlap between groups and does not reflect exact clonotype matches between groups." for chordDiagram(). What does it mean? I thought for example in the plot in question 4 above, it shows whether a cluster has any unique clonotype that is shared with other clusters, and the width would just indicate whether that clone expands in the receiving end cluster?

Sorry this seems to be a source of confusion - so unlike the alluvial graphs, the getCircilize() function does not maintain each individual clonotype, but simplifies them into the relationship with the other groups (or clusters). So it does show unique and overlapping clonotypes between groups. The caveat is that because it drops the specific clonotypes, it makes assumptions when the length of shared clonotypes across all groups exceeds the length of the total number of clonotypes. This may be what is happening in the above example - I will need to look closely.

> 6. Is the warning from chordDiagram an error of concern?

Nope - just a message from the use of the reshape2 function, I added a suppression to this message that is now in the dev version.

> 7. From this clonalOverlap(), the orange indicates the highest overlap coefficient between sample A and sample B (i.e., sample A have much more clonotypes that are also present in sample B than other samples). But, when I plotted using clonesizeDistribution(), why were sample A and B on an entire oppsite branch of the tree below?

The ```clonesizeDistribution()``` is fitting a mixed model gamma-GPD and Pareto model to the clonesize information from the samples - it is not directly looking at the overlap of clones. I think the powerTCR package (which the function is a wrapper for) has a good [vignette](https://bioconductor.org/packages/release/bioc/vignettes/powerTCR/inst/doc/powerTCR.html) that explains the method.

> 8. scatterClonotype() says "The clonotypes will be categorized by counts into singlets or multiplets, either exclusive or shared between the selected samples." From the plot below, does it mean the red dots are the clones that are shared between the 2 samples graphed? And, the size of the dots represent the sum of the this clone count in sample A and sample B?

This depends on the version you are using - v 1.3.2 (current dev version) has a dot.size parameter for ```scatterClonotype()```, where total is the sum clonotypes from the x and y-axis. dot.size can also be used to specify a third sample to compare and use for size (this was a request to match the original visualization). In the original 1.3.1 version, the dot.size was just the total of the lonotypes from the x and y-axis.

> 9. alluvialClonotypes() plot shows whether there is a unique clone that shared among 3 variables (3 columns). But the middle column for example representing the number of clusters 0-22. Why this numbering is not in order; is it because it is arranged by how big the overlap in proportion of a unique clonotype?

After the first columm/stratum, the subsequent columns are arranged by the ggalluvial package for convenience of drawing the cord/alluvial portion. If you'd like to have more control over the plotting - check out the ggalluvial [website](https://corybrunson.github.io/ggalluvial/).

> 10. clusterTCR() clusters the clones by how similar their sequences are. Is the x-axis different cluster ID?

Yes the x-axis is the different cluster IDs

> 11. quantContig() graph appears to have orange/red color groups and then a more blue on the right side. Is there any 
> meaning` behind this color scheme?

Nope - just a color palette. You can change colors on the plot by using 

```
quantContig() + scale_fill_manual(values = c(x,y,z))
```

**Comment by denvercal1234GitHub** [comment]
Thank you very much, Nick. I emailed you the expression2ListCluster and Seurat objects.

**Comment by ncborcherding** [comment]
Hey Quang,

Just got a chance to take a look at your data (thanks for sending it).

> 3. In this compareClonotypes() graph of expression2ListCluster object, it looks like cluster 20 and 22 do not share any clonotype with any other cluster. But, when I graphed the regular combined Seurat object (with TCR info transfered) in a chordDiagram, there seems to be faint line going from cluster 20 and 22 to other clusters. Why is there a discrepancy?

I think what is happening here is that compare ```compareClonotypes()``` is comparing only a specific number of clones using the **numbers** parameter - so it is just a sample of the clones.

<img width="649" alt="Screen Shot 2021-07-16 at 5 19 44 PM" src="https://user-images.githubusercontent.com/22754118/126013981-d3c118ef-73c3-467f-aad8-7843037a4103.png">

There are a total of 46 unique clonotypes in cluster 22 with overlap between several clusters/clones. Here is the output of 
```View(sharing)```

<img width="509" alt="Screen Shot 2021-07-16 at 5 20 09 PM" src="https://user-images.githubusercontent.com/22754118/126014100-a6df5069-5851-4eac-a5ad-d0e8e1838ac2.png">

So there are indeed overlapping clonotypes, a quick check for sanity would be to use ```clonalOverlap()```
<img width="696" alt="Screen Shot 2021-07-16 at 5 28 45 PM" src="https://user-images.githubusercontent.com/22754118/126014351-63c96929-b9a6-4712-bad0-588fba6cbf89.png">

For now I am going to close this - I am still working on a newer version of the ```getCirclize``` that makes less assumptions

**Comment by denvercal1234GitHub** [comment]
Awesome. Thank you @ncborcherding for your help. Looking forward to the new version of getCirclize and potentially the visualization similar to Cytoscape. Have a good week.

**Comment by denvercal1234GitHub** [comment]
Hi @ncborcherding -- Sorry to reopen these questions, but it is still a bit unclear to me. Thank you again for your help!

**Regarding question 3, "I think what is happening here is that compare compareClonotypes() is comparing only a specific number of clones using the numbers parameter - so it is just a sample of the clones".** 

I am unsure if this were the issue, but likely something is strange with the compareClonotype()? 

This is because when I set numbers = NULL (which is supposed to take all clones?), compareClonotypes(expression2List by cluster object) graph still does not show any shared clonotype between cluster 22 and any other clusters. It does, however, shows a shared clonotype between cluster 20 and cluster 2 when I called cloneCall="aa" or = "nt". 

<img width="201" alt="Screen Shot 2021-08-11 at 9 23 50 PM" src="https://user-images.githubusercontent.com/62179082/129098002-22db64e6-7618-42e2-8c59-6d14a7dd437c.png">


**In the "sharing" object above:**

1. What are those numbers on the first (unlabelled) column? 
2. You got 46 unique clones from finding the number of rows of the "c22" object? 
3. How was the "Proportion" here calculated? Is it the proportion of a clone over the total number of clones in a given cluster?

**Comment by ncborcherding** [comment]
> I am unsure if this were the issue, but likely something is strange with the compareClonotype()?

I think you are probably encountering the limits of the alluvial graphing - when I wrote the function, I did not expect to have users graph all the clones per cluster. I think you should compare your compareClonotype() results with clonalOverlap() output, using the same cloneCall. 

> What are those numbers on the first (unlabelled) column?

Is this a repeated question from below or what column are you talking about

> How was the "Proportion" here calculated? Is it the proportion of a clone over the total number of clones in a given cluster?

Proportion is calculated by the number unique clonotypes over the total number of clones across the list element - so in your case, examining clusters, you are correct. 

> Why is it that the shared clonotype is detected only when examining the "to" to "from" and not when I did "from" to "to"? Cluster 22 is shown below as an example.

The chord diagram requires a relational data frame. In order to do this, `getCirclize()` takes essentially an overlap matrix and simplifies it to remove the repetitive comparison Cluster 1 --> Cluster 2 is the same number as Cluster 2 --> Cluster 1. So the function sorts it numerically (eliminating the repeated Cluster 2 --> Cluster 1) and then after this organization puts the "from" and "to" as column headers. In your screenshot the "To" and "From" are interchangeable. 

> If "value" is just 0 (i.e., no shared clonotype), why is it still listed?

Because the function getCirclize evaluates each cluster in regards to one another. It would be an extra line of code to eliminate the 0s and it is not necessary as it does not get drawn in the chordDiagram()

> What are the numbers on the first column in question 4 image?

Like 111, 112, etc? Those are just the row numbers corresponding to the data frame.

**Comment by denvercal1234GitHub** [comment]
Hi Nick, 

> Is this a repeated question from below or what column are you talking about

Sorry for the confusion. I meant the first column (without column heading) of the table output from compareClonotypes(). So I guess they are also simply the row numbers of the data frame. 

Also, why does the output of occupiedscRepertoire(Seurat object with TCR transferred, x.axis = "cluster"), which graphs the cell counts categorized into cloneType frequencies does **_not_** agree with the output of . Which function is the correct one to examine which clusters do have the most expanded clones?

EX: 
Here showing clusters 1, 2, 3 having the most highly expanded clones (in red, cloneType = Hyperexpanded) 
<img width="366" alt="Screen Shot 2021-08-12 at 11 47 29 AM" src="https://user-images.githubusercontent.com/62179082/129184479-f313e29c-6ea4-4060-831b-6822ee25e07c.png">

Yet, from clonalHomeostasis(), clusters 1 and 2 did not show them containing any hyperexpanded clones, but now cluster 8 is being detected as having hyperexpanded clones. 
<img width="228" alt="Screen Shot 2021-08-12 at 11 49 49 AM" src="https://user-images.githubusercontent.com/62179082/129184758-a30e410f-5b8a-46e1-a3b5-5d784da0f6c0.png">


Thank you again Nick for your prompt responses, as always!

**Comment by ncborcherding** [comment]
Hey Quang, 

I would anticipate there would be a difference between ```occupiedscRepertoire()``` vs ```clonalHomeostasis(expression2list object, group = "cluster ID")``` - they have two different calculations for the proportion. 

In ```occupiedscRepertoire()```, the frequency/cloneType and proprotion is all based on the ```combineExpression()``` call, so it is across all clusters. 

In ```clonalHomeostasis(expression2list object, group = "cluster ID")```, the frequency calculation will be by cluster.

Hope that helps,
Nick

**Comment by denvercal1234GitHub** [comment]
I see. Thank you very much, Nick. Though, I am still a bit confused how I should calculate the clone frequency. 

My data have 2 datasets (R5pos and R5neg) that were merged before performing clustering. Some clusters ended up having most of their cells being R5pos. 

In this case, if I want to see whether the predominantly R5pos clusters are more frequently have hyperexpanded clones compared to R5neg clusters, does it make sense to calculate the clonetype frequency using groupBy = "ID" in the combineExpression()? 

I am unsure because indeed the total number of clones/cells from all R5pos clusters combined is different than that from all R5neg clusters combined, so it would not be a fair comparison, right?

**Comment by denvercal1234GitHub** [comment]
Hi Nick -- Thank you so much! I have emailed you the expression2List object with the new metadata R5status_clusterID column.
