### ISSUE TITLE
Using your package having whole PBMC

### ISSUE THREAD

**Issue by beginner984** [ncborcherding/scRepertoire#95]
Hello all

I have only **_scRNA-seq 10x PBMCs_** of cancer survivors (cancer free after 5 years) and controls.

My boss has asked me

T cell analysis – differences between samples (scRNAseq)
Can we identify a/b or g/d pairs for individual T cells

Is there anyway to do TCR analysis just by **_just having scRNA-seq data_** from using your package or I need TCR sequencing data itself?

Thank you so much for any link, idea, tutorial, paper, etc

**Comment by ncborcherding** [comment]
Hey beginner984, 

Thanks for reaching out. 

As of right now, scRepertoire really only supports the paired scRNA/TCR sequencing approach. Based on my experience - just relying on RNA gets a little confusing, as single-cells RNA can show cells with multiple TCR loci - but it is do-able. Let me see if I can dig up a paper I saw, where they looked at the TCRBV genes by cluster and were able to get some degree of specificity by cluster. 

 Depending on your sequencing approach - you may be able to recover the TCR information using [TRUST4](https://github.com/liulab-dfci/TRUST4). This approach works with 5' sequencing though, so it might not work for you. 

I am going to close this "issue" because it is not a problem related to the code, however, please feel free to [reach out to me](mailto:ncborch@gmail.com) anytime as you get started and I am more than willing to help. 

Nick
